title: Scott Briden
description: Enterprise Data & Analytics Strategy, Lakehouse Architecture, Business Intelligence Modernization, and Analytics Operating Models.

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

show_excerpts: false
